import type { Exercise } from '@/src/types';

export const exercises: Exercise[] = [
  {
    id: 'gentle-jaw-stretch',
    name: 'Gentle Jaw Stretch',
    description: 'Slowly open and close your jaw to increase mobility.',
    instructions: [
      'Sit upright with shoulders relaxed',
      'Place your tongue on the roof of your mouth',
      'Slowly open your mouth as wide as comfortable',
      'Hold for the specified time',
      'Slowly close your mouth',
    ],
    category: 'stretch',
    durationSeconds: 30,
    reps: 5,
    holdSeconds: 6,
    difficulty: 1,
    illustration: 'gentle-jaw-stretch',
  },
  {
    id: 'resisted-opening',
    name: 'Resisted Opening',
    description: 'Strengthen jaw muscles with gentle resistance.',
    instructions: [
      'Place your thumb under your chin',
      'Slowly open your mouth while pushing gently against your chin',
      'Hold for the specified time',
      'Slowly close your mouth',
    ],
    category: 'strengthen',
    durationSeconds: 30,
    reps: 5,
    holdSeconds: 6,
    difficulty: 2,
    illustration: 'resisted-opening',
  },
  {
    id: 'lateral-jaw-movement',
    name: 'Lateral Jaw Movement',
    description: 'Move your jaw side to side to improve range of motion.',
    instructions: [
      'Place a thin object (like a tongue depressor) between your front teeth',
      'Slowly move your jaw to the left',
      'Hold briefly, then return to center',
      'Slowly move your jaw to the right',
      'Hold briefly, then return to center',
    ],
    category: 'stretch',
    durationSeconds: 45,
    reps: 5,
    holdSeconds: 3,
    difficulty: 2,
    illustration: 'lateral-jaw',
  },
  {
    id: 'chin-tuck',
    name: 'Chin Tuck',
    description: 'Improve posture and reduce TMJ strain from forward head position.',
    instructions: [
      'Sit or stand with your back straight',
      'Pull your chin straight back, creating a double chin',
      'Hold for the specified time',
      'Release and repeat',
    ],
    category: 'posture',
    durationSeconds: 30,
    reps: 10,
    holdSeconds: 3,
    difficulty: 1,
    illustration: 'chin-tuck',
  },
  {
    id: 'masseter-massage',
    name: 'Masseter Massage',
    description: 'Release tension in the main chewing muscle.',
    instructions: [
      'Place your fingers on your cheeks, just above the jawline',
      'Apply gentle circular pressure',
      'Move slowly along the muscle from ear to chin',
      'Increase pressure gradually as tolerated',
    ],
    category: 'massage',
    durationSeconds: 60,
    reps: 1,
    holdSeconds: 0,
    difficulty: 1,
    illustration: 'masseter-massage',
  },
  {
    id: 'goldfish-partial',
    name: 'Goldfish Exercise (Partial)',
    description: 'Gentle controlled jaw opening with tongue guidance.',
    instructions: [
      'Place your tongue on the roof of your mouth',
      'Place one finger on your TMJ and one on your chin',
      'Drop your lower jaw halfway open',
      'Close your mouth slowly',
    ],
    category: 'stretch',
    durationSeconds: 30,
    reps: 6,
    holdSeconds: 5,
    difficulty: 1,
    illustration: 'goldfish-partial',
  },
  {
    id: 'deep-breathing-jaw',
    name: 'Jaw-Focused Deep Breathing',
    description: 'Combine deep breathing with conscious jaw relaxation.',
    instructions: [
      'Close your eyes and let your jaw hang slightly open',
      'Breathe in slowly through your nose for 4 seconds',
      'Hold for 4 seconds, noticing any jaw tension',
      'Exhale slowly through your mouth for 6 seconds',
      'Let your jaw relax more with each exhale',
    ],
    category: 'relaxation',
    durationSeconds: 120,
    reps: 8,
    holdSeconds: 4,
    difficulty: 1,
    illustration: 'deep-breathing',
  },
  {
    id: 'neck-side-stretch',
    name: 'Neck Side Stretch',
    description: 'Release neck tension that contributes to TMJ pain.',
    instructions: [
      'Sit upright with shoulders relaxed',
      'Slowly tilt your head to the right, ear toward shoulder',
      'Hold for the specified time',
      'Return to center',
      'Repeat on the left side',
    ],
    category: 'stretch',
    durationSeconds: 60,
    reps: 3,
    holdSeconds: 10,
    difficulty: 1,
    illustration: 'neck-side-stretch',
  },
];
