export const Strings = {
  app: {
    name: 'JawEase',
    tagline: 'Relief starts here',
  },
  tabs: {
    today: 'Today',
    exercises: 'Exercises',
    progress: 'Progress',
    settings: 'Settings',
  },
  onboarding: {
    welcomeHeading: 'Take Control of\nYour Jaw Health',
    welcomeSubtext: 'Daily exercises. Pain tracking.\nReal progress.',
    welcomeCta: 'Get Started',
    symptomsTitle: 'What symptoms do you experience?',
    symptomsSubtext: 'Select all that apply',
    baselineTitle: 'How is your jaw feeling right now?',
    painDescriptors: {
      none: 'No pain — great!',
      mild: 'Mild discomfort',
      moderate: 'Moderate pain',
      significant: 'Significant pain',
      severe: 'Severe pain',
    },
    reminderTitle: 'Set your daily reminder',
    reminderSubtext: 'A daily reminder helps build your exercise habit.',
    reminderMorning: 'Morning (8:00 AM)',
    reminderEvening: 'Evening (7:00 PM)',
    reminderCustom: 'Choose a time',
    reminderDenied: 'You can enable notifications later in Settings.',
    emailTitle: 'Stay on track',
    emailSubtext: "We'll send weekly progress summaries and exercise tips",
    emailCaption: 'No spam. Unsubscribe anytime.',
    emailPlaceholder: 'your@email.com',
    emailLabel: 'Email address',
    emailCta: 'Continue',
    paywallHeading: 'Your personalised plan is ready',
    paywallBenefits: [
      'Unlimited guided exercises',
      'Advanced pain analytics & insights',
      'Personalised recovery programs',
      'Weekly progress reports',
      'Priority support',
    ],
    paywallCta: 'Start Free Trial — 3 Days Free',
    paywallDismiss: 'Maybe later',
    paywallMonthly: '£4.99/month',
    paywallAnnual: '£29.99/year',
    paywallAnnualBadge: 'SAVE 50%',
    paywallLifetime: '£49.99 once',
  },
  symptoms: {
    jaw_pain: 'Jaw Pain',
    jaw_clicking: 'Jaw Clicking',
    teeth_grinding: 'Teeth Grinding',
    headaches: 'Headaches',
    neck_tension: 'Neck Tension',
    ear_pain: 'Ear Pain',
    jaw_locking: 'Jaw Locking',
    facial_pain: 'Facial Pain',
  },
  triggers: {
    stress: 'Stress',
    poor_sleep: 'Poor Sleep',
    food: 'Hard/Chewy Food',
    weather: 'Weather Change',
    caffeine: 'Caffeine',
    alcohol: 'Alcohol',
  },
  painLevels: {
    none: 'No pain',
    mild: 'Mild',
    moderate: 'Moderate',
    severe: 'Severe',
    extreme: 'Extreme',
  },
} as const;
