export const Strings = {
  app: {
    name: 'JawEase',
    tagline: 'Relief starts here',
  },
  tabs: {
    today: 'Today',
    exercises: 'Exercises',
    progress: 'Progress',
    settings: 'Settings',
  },
  onboarding: {
    welcomeHeading: 'Take Control of\nYour Jaw Health',
    welcomeSubtext: 'Daily exercises. Pain tracking.\nReal progress.',
    welcomeCta: 'Get Started',
    symptomsTitle: 'What symptoms do you experience?',
    symptomsSubtext: 'Select all that apply',
    baselineTitle: 'How is your jaw feeling right now?',
    painDescriptors: {
      none: 'No pain — great!',
      mild: 'Mild discomfort',
      moderate: 'Moderate pain',
      significant: 'Significant pain',
      severe: 'Severe pain',
    },
    reminderTitle: 'Set your daily reminder',
    reminderSubtext: 'A daily reminder helps build your exercise habit.',
    reminderMorning: 'Morning (8:00 AM)',
    reminderEvening: 'Evening (7:00 PM)',
    reminderCustom: 'Choose a time',
    reminderDenied: 'You can enable notifications later in Settings.',
    emailTitle: 'Stay on track',
    emailSubtext: "We'll send weekly progress summaries and exercise tips",
    emailCaption: 'No spam. Unsubscribe anytime.',
    emailPlaceholder: 'your@email.com',
    emailLabel: 'Email address',
    emailCta: 'Continue',
    paywallHeading: 'Your personalised plan is ready',
    paywallBenefits: [
      'Unlimited guided exercises',
      'Advanced pain analytics & insights',
      'Personalised recovery programs',
      'Weekly progress reports',
      'Priority support',
    ],
    paywallCta: 'Start Free Trial — 3 Days Free',
    paywallDismiss: 'Maybe later',
    paywallMonthly: '£4.99/month',
    paywallAnnual: '£29.99/year',
    paywallAnnualBadge: 'SAVE 50%',
    paywallLifetime: '£49.99 once',
  },
  symptoms: {
    jaw_pain: 'Jaw Pain',
    jaw_clicking: 'Jaw Clicking',
    teeth_grinding: 'Teeth Grinding',
    headaches: 'Headaches',
    neck_tension: 'Neck Tension',
    ear_pain: 'Ear Pain',
    jaw_locking: 'Jaw Locking',
    facial_pain: 'Facial Pain',
  },
  triggers: {
    stress: 'Stress',
    poor_sleep: 'Poor Sleep',
    food: 'Hard/Chewy Food',
    weather: 'Weather Change',
    caffeine: 'Caffeine',
    alcohol: 'Alcohol',
  },
  exerciseFlow: {
    routineTitle: "Today's Routine",
    begin: 'Begin',
    pause: 'Pause',
    resume: 'Resume',
    skip: 'Skip',
    skipRest: 'Skip Rest',
    rest: 'Rest',
    nextUp: 'Next up:',
    hold: 'Hold...',
    release: 'Release...',
    rep: 'Rep',
    sessionComplete: 'Session Complete!',
    greatWork: 'Great work! Your jaw will thank you.',
    duration: 'Duration',
    exercisesDone: 'Exercises',
    streakLabel: 'Streak',
    howsYourJaw: "How's your jaw feeling now?",
    done: 'Done',
    painImproved: 'Nice improvement!',
    routineCompleted: 'Completed today!',
    startRoutine: 'Start Routine',
  },
  painLevels: {
    none: 'No pain',
    mild: 'Mild',
    moderate: 'Moderate',
    severe: 'Severe',
    extreme: 'Extreme',
  },
  tips: [
    'Apply a warm compress for 10 minutes to relax jaw muscles',
    'Avoid chewing gum — it overworks the masseter',
    'Rest your tongue on the roof of your mouth with teeth apart',
    'Sleep on your back to reduce jaw pressure',
    'Practice belly breathing when you notice jaw clenching',
    'Massage your masseter muscle in circular motions for 30 seconds',
    'Cut food into small pieces to reduce jaw strain',
    'Take breaks from screens — tension travels to your jaw',
    'Stay hydrated — dehydration increases muscle tension',
    'Notice if you clench during stress — awareness is the first step',
  ],
} as const;
